### PR TITLE
init Actions

### PR DESCRIPTION
**Pull request by mhwilkes**
Simple Actions setup to facilitate CI in the future

### CODE REVIEW

**Comment by mhwilkes** [comment]
Tests currently passing. When we get some testing done we can hook that into the pipeline!

**Comment by mhwilkes** [comment]
If you have anything to put into this or possibly some tests to write @Orang-utan feel free to add, otherwise when you approve we can close this.

**Comment by Orang-utan** [comment]
is this for heroku deployment? cuz if that's the case you actually dont need to do any setups

**Comment by mhwilkes** [comment]
No i just set this up so that when we push to the repository it can run a test suite. Like it would in Heroku but we don't have heroku setup yet. It's possible this is not necessary but I wanted to learn about it a little.

**Comment by Orang-utan** [comment]
ohh ok! cool sgtm!

**Pull request merged**
